name: build Image
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: '填写构建的服务名'
        required: true
        default: 'nginx'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./.github/workflows/script/${{ github.event.inputs.server_name }}/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 脚本授权
        run: ls && chmod +x ./build-image.sh

      - name: 构建镜像
        run: ./build-image.sh

      - name: 压缩镜像
        run: tar -czf images.tar.gz *.tar  && ls

      - name: 上传脚本
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: ./.github/workflows/script/${{ github.event.inputs.server_name }}/images.tar.gz
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

      - name: Clean up intermediate files
        run: |
          rm *.tar
