name: build Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 '
        required: true
        default: 'ros:noetic_dong'  # 设置默认的 Docker  

jobs:
  pull_and_package:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        #shell: bash
        working-directory: ./script
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: chmod 
        run: chmod +x ./build-images.sh
      - name: build Images
        run: ./build-images.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-tar
          path: x86-64-image.tar.gz
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
      - name: Clean up intermediate files
        run: rm *-amd64.tar
